name: wisdom
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.5.4
  flutter_zoom_drawer: ^3.0.3
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^7.4.0
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.7
  #  flutter_cupertino_date_picker_fork: ^1.0.7
  numberpicker: ^2.1.1
  flutter_native_splash: ^2.2.16
  sqflite: ^2.2.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  swipe_refresh: ^1.0.2
  flutter_widget_from_html: ^0.9.1
  translator: ^0.1.7
  clipboard: ^0.1.3
  speech_to_text: ^6.1.1
  lottie: ^2.2.0
  platform_device_id: ^1.0.1

  # Firebase push notification
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1

  easy_localization: ^3.0.1
  provider: ^6.0.5

  flutter_local_notifications: ^13.0.0
  awesome_notifications: ^0.7.4+1
  workmanager: ^0.5.1
  background_fetch: ^1.1.4

  expandable: ^5.0.1
  flutter_tts: ^3.6.3

  # google ads
  google_mobile_ads: ^2.3.0

  #app launcher
  external_app_launcher: ^3.1.0

  #Text selection menu
  selectable: ^0.2.11

  # Share for text, images, file
  share_plus: ^5.0.0
  cupertino_icons: ^1.0.2

  #animation for save words icon
  add_to_cart_animation: ^2.0.3

  # state management
  jbaza:
    git:
      url: https://github.com/Javoh29/Jbaza

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/
    - fonts/
    - assets/waio_dictionary.db

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
          style: normal

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:

  color: "#0063A4"
  image: assets/images/logo_icon_white.png
  color_dark: "#1F1D2B"

  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
    image: assets/images/logo_icon_white_12.png

    color: "#0063A4"
    color_dark: "#1F1D2B"

  android: true
  ios: true
  web: false

  color_android: "#0063A4"
  color_dark_android: "#1F1D2B"
  color_ios: "#0063A4"
  color_dark_ios: "#1F1D2B"

  fullscreen: true